/* Generated by           cobc 3.1.2.0 */
/* Generated from         perform-loop.cob */
/* Generated at           Jan 04 2023 22:28:52 */
/* GnuCOBOL build date    Dec 10 2022 19:56:17 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C perform-loop.cob */

/* Program local variables for 'PERFORM-LOOP' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[1] __attribute__((aligned));	/* COUNTER */

/* End of local data storage */


/* Fields (local) */
static cob_field f_8	= {1, b_8, &a_1};	/* COUNTER */

/* End of fields */

