/* Generated by           cobc 3.1.2.0 */
/* Generated from         perform-loop.cob */
/* Generated at           Jan 04 2023 22:28:52 */
/* GnuCOBOL build date    Dec 10 2022 19:56:17 */
/* GnuCOBOL package date  Dec 23 2020 12:04:58 UTC */
/* Compile command        cobc -C perform-loop.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x10,   1,   0, 0x0000, NULL};

